### ISSUE TITLE
Use `lubridate` for date conversion?

### ISSUE THREAD

**Issue by Aariq** [az-digitalag/Rainman-swp#3]
https://github.com/cct-datascience/Rainman-swp/blob/425b48c42a40f4e9dd6fcad72bac61a2eb286079/scripts/02_exploration_halfhourly.Rmd#L78

This line errors for me with `character string is not in a standard unambiguous format` but `lubridate::mdy_h()` handles it fine.
```
readr::read_csv("./data/irrigation.csv") %>%
  mutate(dt = lubridate::mdy_h(paste0(date, " 12"), tz = "America/Phoenix"))
```

**Comment by jessicaguo** [comment]
Thank you!
